<br>

## Final project preliminaries and explorations

<font color="Teal"><b>Exploring how much an idea "pushes back" - including its technologies, libraries, and online resources ...</b></font>



<br>

#### Here are the online [cs35 project guidelines](https://docs.google.com/document/d/1DwoOJCy6GGECvzSOE4BDPVcEgVtvChglnz03-uxx7mA/edit?tab=t.0)  with more details.

<br>


#### **What you've tried**
+ What are the things you've tried <b><u>so far</u></b> - and how has it gone?  
  + This is the most important effort!  
  + <b>Note</b>: If you have _lots_ of ideas and can't decide... look for online guides or walkthroughs for several of them and see which are most promising (and interesting!)
  + include, here in the Python cells above/below, the explorations and/or experiments you've pursued
  + if you're using plain-python files or other notebook files, submit those, in addition or instead
    + <font size="-2">if you submit other files instead, include these reflections in the files you submit...</font>
  + include any other <i>small</i> data files/links/resources you've collected

<br>
<br>

#### **Your Project Plan,** <font size="-1">as of this moment...</font>

+ <b><font color="DodgerBlue">Share</font></b> a paragraph or so on your project exploration so far -- and your summer of the idea/plan + its background
  + This is intentionally ***progress-first***
  + **Try things out** before dedicating too much to a single, specific path...
+ <b><font color="Coral">Share</font></b>: &nbsp; What resources/libraries/walkthroughs have you found?
+ <b><font color="Coral">Share</font></b>: &nbsp; What datasets are you using? <font size="-1">if applicable for your project</font>

<br>
<br>

#### **Looking ahead**
+ Specifically, what task do you plan to try <b><u>next</u></b>?
+ More generally, how do you plan to go _beyond_ existing resources...
  + If it's not shared above, describe how you envision _personalizing_ and/or _individualizing_ your project...

<br><br>
<hr>
<br><br>

Feel free to use this notebook to summarize your prelimiaries so far ...

<br>

... ***or*** &nbsp;&nbsp; include your responses to these questions in other  notebooks or plain-python files!

<br><br>
<hr>
<br><br>

[vision] Direction, Idea, and Feasible Set
My project explores the intersection of machine learning and creativity through Algorithmic Music Generation. The core idea is to treat musical notes as numerical data sequences, similar to how we treated pixels in the digits assignment, to train a Neural Network that can predict the next logical note in a melody. My ideal, big-picture conclusion is to create a "Digital Composer" that can take a short user-provided musical phrase and "dream" a harmonically consistent continuation. For this term, I believe feasible final progress would be a functional model that successfully predicts the next pitch in a sequence from a specific genre (such as classical or early video game music) and exports that result as a playable MIDI file.

[starting points] Research, Walkthroughs, and Libraries
My preliminary research has been focused on finding the right "bridge" between music files and Python. I am basing the technical foundation of my project on documentation for the mido and pretty_midi libraries, which achieve the critical task of converting complex MIDI messages into numerical arrays that Scikit-Learn can process. I imagine personalizing this starting point by applying our specific class techniques, like the MLPRegressor and the "rolling window" feature engineering we discussed, rather than using the pre-built deep learning black boxes often found in online guides. Software-wise, I have successfully installed mido and sklearn, and I am able to read basic file metadata. However, I am currently stuck on normalizing note durations across different tempos, so I am exploring the music21 toolkit to see if it works better for preprocessing. Data-wise, I plan to work with the Lakh MIDI Dataset or a collection of Classic NES MIDI files. I have been able to show naive access to this data by extracting raw pitch values into a list and restructuring them into a "Features vs. Target" format for the Neural Network.

[coding exploration] Naive Data Access
(in code cell below)

In [1]:
import pandas as pd
import numpy as np
from sklearn.neural_network import MLPRegressor

# Preliminary Exploration: Converting a Melody into "Feature Windows"
# Example sequence: C -> D -> E -> F -> G -> A -> B -> C
melody = [60, 62, 64, 65, 67, 69, 71, 72] 

def prepare_melody_data(sequence, window_size=3):
    X, y = [], []
    for i in range(len(sequence) - window_size):
        X.append(sequence[i:i + window_size]) # The "context" notes
        y.append(sequence[i + window_size])    # The "target" next note
    return np.array(X), np.array(y)

# Creating the training set (e.g., use 3 notes to predict the 4th)
X_train, y_train = prepare_melody_data(melody)

print("Musical Feature Matrix (X):\n", X_train)
print("\nMusical Target Note (y):\n", y_train)

# Proof of Concept: Can the NNet 'hear' the pattern?
nn_composer = MLPRegressor(hidden_layer_sizes=(15, 15), max_iter=1000, random_state=42)
nn_composer.fit(X_train, y_train)
print("\nStatus: Preliminary NNet training on melodic data successful.")

Musical Feature Matrix (X):
 [[60 62 64]
 [62 64 65]
 [64 65 67]
 [65 67 69]
 [67 69 71]]

Musical Target Note (y):
 [65 67 69 71 72]

Status: Preliminary NNet training on melodic data successful.


[next plans]
Moving forward, my immediate next steps are to curate a small, clean folder of MIDI files from the same musical genre to ensure the model has a consistent "style" to learn. By the April 19 proposal deadline, I plan to have a script that can "flatten" multiple MIDI files into a single CSV. I also intend to experiment with whether treating the notes as categories (MLPClassifier) or continuous frequencies (MLPRegressor) results in a more "musical" output during the hallucination phase.

In [2]:
#
#  Feel free to interleave markdown or plain-text throughout...
#
#       If your project doesn't work well with notebooks, plain-python is 100% ok.
#

Suggestions:

Tech Stack:

pretty_midi - best for reading/writing MIDI, cleaner than mido (which may not be needed)

mido - lower-level and good for inspection, not as good for this project as pretty_midi

music21(MIT) - heavier but good for music theory operations (ie. key detection, chord analysis). Only pull if needed

scikit-learn - yay good! MLPRegressor / MLPClassifier, kNN, decision trees

numpy / pandas - good yes

IPython.display.Audio / fluidsynth (via pyfluidsynth) for playing MIDI in a notebook during demo. This will be important for presentation day!!

On your MLPRegressor vs MLPClassifier question: I'd lean toward Classifier. Notes are discrete categories (MIDI pitch 60 ≠ "halfway between 59 and 61" in any musical sense — they're different notes). A regressor will happily predict pitch 63.7, which isn't a note. Classifier also gives you probability distributions you can sample from, which produces more interesting/varied output than always picking the argmax. Sampling from the top-k predictions is how you get "creativity" without a big model.

"Pi music" can map the digits of pi (or any number sequence) to musical notes. This would be a good baseline because it is:
- deterministic but sounds pseudo-random
- trivial to implement (1 function)

Baseline 1: Uniformly random notes (sounds like noise)
Baseline 2: π-digit or frequency-weighted random (slightly better — uses pitch distribution from training data)
Your model: MLP with rolling-window features (should capture local melodic patterns)
Evaluation: Accuracy on next-note prediction + qualitative listening

Suggested better datasets:

Classic NES MIDI (Chip's Challenge MIDI, NES-MDB) — Small, melodically simple, stylistically consistent. Great choice.
JSB Chorales — Bach four-part chorales, very popular ML-research dataset, highly structured.
Nottingham Dataset — Folk tunes, monophonic melodies, extremely clean.

one genre, ~20-50 files. Consistency beats volume.

some future extentions worth exploring:

Intervals instead of absolute pitches (differences between consecutive notes) — this makes the model key-invariant, so a melody in C major teaches it something useful about the same melody transposed to G major.

Include note duration as a second feature channel.

Represent pitch modulo 12 (pitch class) alongside octave — captures that C in different octaves are "the same note."

Since submitting our initial exploratiom, we have changed our approach in a few important ways.
The biggest shift we are implementing is reframing the project around baseline-to-improvement narrative rather than jumping straight into "build a composer." Based on feedback from Professor Dodds, we would start with random generation and algorithmically improve from there. We plan to use three systems simultaneously:

1. uniform random note generation
2. a "pi-music" or distribution-weighted random baseline that samples from the pitch frequencies observed in our training data
3. our MLP-based next-note predictor

This allows us to report accuracy numbers and play audio clips of each system for comparison.

We also switched from MLPRegressor to MLPClassifier. Previously, it didn't make sense to treat pitches as continuous values becuase it let the model predict nonexistent "in-between" notes, that didn't make musical sense. Classifications let us sample from predicted probability distribution, which is both more musically meaningful and produces a more interesting output than picking a most likely next note.

We're planning to use ~30 Classic NES MIDI files so the model learns a coherent style. We got pretty_midi working end-to-end for reading pitches and durations, and we wrote a script that flattens multiple MIDI files into a single feature matrix using the rolling-window approach from the digits assignment. We're also exploring representing notes as intervals (pitch differences) rather than absolute pitches, which should help the model generalize across different keys.

Our next steps:
- finish the multi-file preprocessing pipeline and generate our first unified CSV.
- implement the two random baselines (uniform and distribution-weighted).
- Train MLPClassifier on the full dataset and measure next-note prediction accuracy
- Get MIDI playback working inline in the notebook (via pretty_midi.write() + IPython.display.Audio) so we can demo live on presentation day
If time permits: try a kNN model as a third comparison point, and experiment with temperature-controlled sampling